version: '3.8'
services:
  user-service:
    build: ./backend/user-service
    ports:
      - "3001:3000"
  transaction-service:
    build: ./backend/transaction-service
    ports:
      - "3002:3000"
  goal-service:
    build: ./backend/goal-service
    ports:
      - "3003:3000"
  gateway:
    build: ./backend/gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - transaction-service
      - goal-service
